# Generated by Django 3.2.5 on 2022-06-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['id'], 'verbose_name': 'Rede Social', 'verbose_name_plural': 'Genero'},
        ),
    ]
