# Generated by Django 3.2.5 on 2022-06-21 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.CharField(choices=[('TL', 'Tech Lead'), ('PM', 'Product Manager'), ('ES', 'Engenheiro de Software')], default='--', max_length=2, verbose_name='Profissao'),
            preserve_default=False,
        ),
    ]
