# Generated by Django 3.2.5 on 2022-06-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
