# Generated by Django 3.2.5 on 2022-06-21 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='departament',
            field=models.CharField(choices=[('PEX', 'Investment Plataform'), ('BRK', 'Broker'), ('OB', 'Onboarding'), ('TR', 'Trade')], default='--', max_length=3, verbose_name='Departamento'),
            preserve_default=False,
        ),
    ]
