# Generated by Django 3.2.5 on 2022-06-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_departament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_socialnetwork',
        ),
    ]
