# Generated by Django 3.2.5 on 2022-06-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Funcionário do projeto',
                'verbose_name_plural': 'Funcionários dos projetos',
                'ordering': ['id'],
            },
        ),
    ]
