# Generated by Django 3.2.5 on 2022-06-24 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_order'),
        ('clients', '0007_clientproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ManyToManyField(blank=True, through='clients.ClientProject', to='orders.OrderItem'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
            preserve_default=False,
        ),
    ]
