# Generated by Django 3.2.5 on 2022-06-23 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unitary_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.TextField(default='', max_length=300, verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='project',
            field=models.CharField(default='Projeto sem nome', max_length=50, verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
