# Generated by Django 3.2.5 on 2022-06-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220623_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
