# Generated by Django 3.2.5 on 2022-06-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('address', models.CharField(max_length=200, verbose_name='Endereco')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='Telefone celular')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('job', models.CharField(choices=[('TL', 'Tech Lead'), ('PM', 'Product Manager'), ('ES', 'Engenheiro de Software')], max_length=2, verbose_name='Profissao')),
                ('departament', models.CharField(choices=[('PEX', 'Investment Plataform'), ('BRK', 'Broker'), ('OB', 'Onboarding'), ('TR', 'Trade')], max_length=3, verbose_name='Departamento')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generos.genero')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Funcionário do projeto',
                'verbose_name_plural': 'Funcionários dos projetos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generos.genero')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='project',
            field=models.ManyToManyField(blank=True, through='funcionarios.FuncionarioProject', to='projetos.Projeto'),
        ),
    ]
