# Generated by Django 3.2.5 on 2022-06-26 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date_fabrication', models.DateField(verbose_name='Data Fabricacao')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('job', models.CharField(choices=[('TL', 'Tech Lead'), ('PM', 'Product Manager'), ('ES', 'Engenheiro de Software')], max_length=2, verbose_name='Profissao')),
                ('salary', models.BigIntegerField(verbose_name='Salario')),
                ('departament', models.CharField(choices=[('PEX', 'Investment Plataform'), ('BRK', 'Broker'), ('OB', 'Onboarding'), ('TR', 'Trade')], max_length=3, verbose_name='Departamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamentos.pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento do funcionario',
                'verbose_name_plural': 'Pagamentos dos funcionarios',
                'ordering': ['id'],
            },
        ),
    ]
